<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'About' => '',
    'Backend' => '',
    'Body' => '',
    'Cannot log in registered user' => '',
    'E-mail' => '',
    'Email' => '',
    'Home' => '',
    'If you forgot your password you can reset it <a href="{link}">here</a>' => '',
    'Name' => '',
    'Password reset for {name}' => '',
    'Sorry, we are unable to reset password for email provided.' => '',
    'Thank you for contacting us. We will respond to you as soon as possible.' => '',
    'There was an error sending email.' => '',
    'This email address has already been taken.' => '',
    'This username has already been taken.' => '',
    'Wallet' => '',
    'We already have a user with email {email}' => '',
    'Welcome to {app-name}. Email with your login information was sent to your email.' => '',
    'Your account has been successfully created.' => '',
    '{app-name} | Your login information' => '',
    'Account Settings' => 'Ustawienia konta',
    'Activation email' => 'Email aktywacyjny',
    'Articles' => 'Artykuły',
    'Attachments' => 'Załączniki',
    'Check your email for further instructions.' => 'Sprawdź swój email po dalsze instrukcje',
    'Confirm Password' => 'Potwierdź hasło',
    'Contact' => 'Kontakt',
    'Error while oauth process.' => 'Błąd podczas autoryzacji',
    'Female' => 'Kobieta',
    'Incorrect username or password.' => 'Nieprawidłowa nazwa użytkownika lub hasło',
    'Language' => 'Język',
    'Log in with' => 'Zaloguj się przez',
    'Login' => 'Zaloguj',
    'Logout' => 'Wyloguj',
    'Male' => 'Mężczyzna',
    'Need an account? Sign up.' => 'Potrzebujesz konta? Zarejestruj się',
    'New password was saved.' => 'Nowe hasło zostało zapisane',
    'Page not found' => 'Strony nie znaleziono',
    'Password' => 'Hasło',
    'Profile settings' => 'Ustawienia profilu',
    'Remember Me' => 'Zapamiętaj mnie',
    'Request password reset' => 'Zresetuj hasło',
    'Reset password' => 'Zresetuj hasło',
    'Settings' => 'Ustawienia',
    'Sign up with' => 'Zarejestruj się za pomocą',
    'Signup' => 'Zarejestruj',
    'Subject' => 'Tytuł',
    'Submit' => 'Wyślij',
    'This email has already been taken.' => 'Ten email jest już zajęty',
    'Update' => 'Aktualizuj',
    'User Settings' => 'Ustawienia użytkownika',
    'Username' => 'Nazwa użytkownika',
    'Username or email' => 'Nazwa użytkownika lub email',
    'Verification Code' => 'Kod weryfikacyjny',
    'Your account has been successfully activated.' => 'Twoje konto zostało aktywowane',
    'Your account has been successfully created. Check your email for further instructions.' => 'Twoje konto zostało utworzone. Sprawdź swoją skrzynkę pocztową po dalsze instrukcje',
    'Your account has been successfully saved' => 'Twoje konto zostało zapisane',
    'Your activation link: {url}' => 'Twój kod aktywacyjny {url}',
];
