<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Address' => 'Adres',
    'Back' => 'Cofnij',
    'Edit account' => 'Edytuj konto',
    'Error {code}' => 'Błąd {code}',
    'List of transactions' => 'Lista transakcji',
    'Product' => 'Produkt',
    'Receipt Details' => 'Szczegóły paragonu',
    'Receipt Image' => 'Obraz paragonu',
    'Select company' => 'Wybierz sieć',
    'Select shop' => 'Wybierz sklep',
    'Summary' => 'Podsumowanie',
    'Toggle navigation' => '',
    'Account' => 'Konto',
    'Add' => 'Dodaj',
    'Add Receipt' => 'Dodaj paragon',
    'Add new Company' => 'Dodaj nową kompanię',
    'Add new receipt' => 'Dodaj nowy paragon',
    'Add new shop' => 'Dodaj nowy sklep',
    'Assets' => 'Aktywa',
    'Comments' => 'Komentarze',
    'Count' => 'Ilość',
    'Create' => 'Utwórz',
    'Create first wallet' => 'Utwór pierwszy portfel',
    'Create new wallet' => 'Utwórz nowy portfel',
    'Date' => 'Data',
    'Edit profile' => 'Edytuj profil',
    'Export' => 'Export',
    'Female' => 'Kobieta',
    'Fixed cost' => 'Koszty stałe',
    'Hello, {username}' => 'Witaj, {username}',
    'ID' => 'ID',
    'Import' => 'Import',
    'Incorrect username or password.' => 'Nieprawidłowa nazwa użytkownika lub hasło',
    'Liabilities' => 'Pasywa',
    'List' => 'Lista',
    'Logout' => 'Wyloguj',
    'Main' => 'Główne',
    'Main Report' => 'Raport podsumowujący',
    'Male' => 'Mężczyzna',
    'Member since {0, date, short}' => 'Jesteś z nami od {0, date, short}',
    'My netto value' => 'Moja wartość netto',
    'Name' => 'Nazwa',
    'Password' => 'Hasło',
    'Products' => 'Produkty',
    'Profile' => 'Profil',
    'Receipts List' => 'Lista paragonów',
    'Remember Me' => 'Zapamiętaj mnie',
    'Reports' => 'Raporty',
    'Shop' => 'Sklep',
    'Shops' => 'Sklepy',
    'Sign In' => 'Zaloguj',
    'Sign me in' => 'Zaloguj mnie',
    'Total Price' => 'Cena całkowita',
    'Transactions' => 'Transakcje',
    'Unit Price' => 'Cena jednostkowa',
    'Update' => 'Aktualizuj',
    'Username' => 'Nazwa użytkownika',
];
