<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add new shop' => '',
    'Address' => '',
    'Back' => '',
    'Comments' => '',
    'Count' => 'Ilość',
    'Date' => 'Data',
    'Edit account' => '',
    'Edit profile' => '',
    'Error {code}' => '',
    'Female' => '',
    'ID' => '',
    'Male' => '',
    'Name' => '',
    'Product' => '',
    'Receipt Details' => '',
    'Receipt Image' => '',
    'Select company' => '',
    'Select shop' => '',
    'Shop' => 'Sklep',
    'Toggle navigation' => '',
    'Total Price' => '',
    'Unit Price' => '',
    'Update' => '',
    'Wallet details' => '',
    'Account' => 'Konto',
    'Add' => 'Dodaj',
    'Add Receipt' => 'Dodaj paragon',
    'Add new Company' => 'Dodaj nową kompanię',
    'Add new receipt' => 'Dodaj nowy paragon',
    'Assets' => 'Aktywa',
    'Create' => 'Utwórz',
    'Create first wallet' => 'Utwór pierwszy portfel',
    'Create new wallet' => 'Utwórz nowy portfel',
    'Export' => 'Export',
    'Fixed cost' => 'Koszty stałe',
    'Hello, {username}' => 'Witaj, {username}',
    'Import' => 'Import',
    'Incorrect username or password.' => 'Nieprawidłowa nazwa użytkownika lub hasło',
    'Liabilities' => 'Pasywa',
    'List' => 'Lista',
    'Logout' => 'Wyloguj',
    'Main' => 'Główne',
    'Main Report' => 'Raport podsumowujący',
    'Member since {0, date, short}' => 'Jesteś z nami od {0, date, short}',
    'My netto value' => 'Moja wartość netto',
    'Password' => 'Hasło',
    'Products' => 'Produkty',
    'Profile' => 'Profil',
    'Receipts List' => 'Lista paragonów',
    'Remember Me' => 'Zapamiętaj mnie',
    'Reports' => 'Raporty',
    'Shops' => 'Sklepy',
    'Sign In' => 'Zaloguj',
    'Sign me in' => 'Zaloguj mnie',
    'Transactions' => 'Transakcje',
    'Username' => 'Nazwa użytkownika',
];
